set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Load Vundle itself
Plugin 'VundleVim/Vundle.vim'

" Load testing framework
Bundle "inkarkat/runVimTests"

" Load dependencies
Bundle 'tobyS/vmustache'
Bundle 'SirVer/ultisnips'
